baseURL = "https://inougroup1.github.io/blog/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Static blog update Test"
copyright = "This is a customized copyright."
theme = "hugo-theme-diary-master"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = ""
enableGitalk = false
disableDarkMode=true

# Twitter Card and Open Graph settings
enableOpenGraph = false
enableTwitterCards = false
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

  
   
[[menu.main]]
url = "/post"
name = "Archive"
weight = 1

[[menu.main]]
url = "/categories/category1"
name = "categoryTest1"
weight = 2

[[menu.main]]
url = "/categories/categorytest2"
name = "Categories2"
weight = 3